runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:uHNs2KJ/R85tA2rNIWIAlaoSizDnzzX+JKcxoCKisa0=
  STORAGE_DIR: /tmp
  DB_HOST: localhost
  DB_DATABASE: rajaram_db
  DB_USERNAME: root
  DB_PASSWORD: fuckingrobo#123
  DB_SOCKET: "/cloudsql/rajaram-177117:us-central1:rajaram"
  MYSQL_DSN: mysql:unix_socket=/cloudsql/rajaram-177117:us-central1:rajaram;dbname=rajaram_db

beta_settings:
    # for Cloud SQL, set this value to the Cloud SQL connection name,
    # e.g. "project:region:cloudsql-instance"
    cloud_sql_instances: "rajaram-177117:us-central1:rajaram"
